# Problem Statement:
You work in XYZ Company as a Python developer. The company officials want
you to build a Python program.
**Tasks To Be Performed:**

**1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
value and returns a NumPy array of the given dimension filled with the
given value e.g.: solve((3, 3), 5) will return<br>
[
[5, 5, 5],<br>
[5, 5, 5],<br>
[5, 5, 5]]**

In [25]:
import numpy as np
def array_1(dimensions, value):
    return np.full(dimensions, value)
result= array_1((3, 3), 5)
print(result)


[[5 5 5]
 [5 5 5]
 [5 5 5]]


**2. Create a method that takes n NumPy arrays of the same dimensions,
sums them and returns the answer.**

In [28]:
def sum_arrays(*arrays):
    if all(array.shape == arrays[0].shape for array in arrays):
        return np.sum(arrays, axis=0)
    else:
        raise ValueError("All arrays must have the same shape")
a1 = np.array([[1,2,3],[2,5,8],[8,6,4]])
a2 = np.array([[8,2,0],[4,6,8],[4,3,2]])
r2 = sum_arrays(a1, a2)
print(r2)

[[ 9  4  3]
 [ 6 11 16]
 [12  9  6]]


**3. Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
top-left N X M sub matrix, e.g:
[
[1, 2, 3],<br>
[4, 5, 6],<br>
[7, 8, 9],
]<br><br>
top_left_sub_matrix (matrix, 2, 2) -> should return:<br>
[
[1, 2]<br>
[4, 5]]**

In [31]:
def top_left_sub_matrix(matrix, N, M):
    return matrix[:N, :M]
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
r3 = top_left_sub_matrix(matrix, 2, 2)
print(r3)

[[1 2]
 [4 5]]


**4. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the
bottom-right N X M sub matrix, e.g:<br>
[
[1, 2, 3],<br>
[4, 5, 6],<br>
[7, 8, 9],
]<br>
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed).<br>
[
[5, 6]<br>
[8, 9]
]**

In [41]:
import numpy as np
def sub_matrix(matrix, N, M):
    rows, cols = matrix.shape
    return matrix[rows - N:, cols - M:]
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = sub_matrix(matrix1, 2, 2)
print(result)

[[5 6]
 [8 9]]


**5. Given a 1 D NumPy Array. Write a function that accepts this array as
parameters. The method should return a dictionary with 'mean' and
'std_dev' as key and array's mean and array's standard deviation as
values:<br>
[1, 1, 1]<br>
solution(arr) -> should return :<br>
{'mean': 1.0, 'std_dev': 0.0}**

In [35]:
import numpy as np
def solution(arr):
    mean = np.mean(arr)
    std_dev = np.std(arr)
    return {'mean': mean, 'std_dev': std_dev}
arr = np.array([1, 1, 1])
result = solution(arr)
print(result)

{'mean': 1.0, 'std_dev': 0.0}
