# Problem Statement:
**You work in XYZ Corporation as a Data Analyst. Your corporation has told you to use the NumPy package and do some tasks related to that.<br>
Tasks To Be Performed:**


**1. Create a 3x3 matrix array with values ranging from 2 to 10.**

In [6]:
import numpy as np 
a=np.arange(2,11).reshape(3,3)
print("Task 1 - 3x3 Matrix:\n",a)

Task 1 - 3x3 Matrix:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**2. Create a NumPy array having user input values and convert the integer type to the float type of the elements of the array. For instance:<br>
Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]**

In [52]:
import numpy as np
user_input = input("Enter array separated by spaces: ").split()
array = np.array(user_input, dtype=int)
array_float = array.astype(float)
print("\nOriginal array:\n", array)
print("Array converted to float type:\n", array_float)


Enter array separated by spaces:  1 2 3 4



Original array:
 [1 2 3 4]
Array converted to float type:
 [1. 2. 3. 4.]


**3. Write a NumPy program to append values to the end of an array. For instance: Original array: [10, 20, 30] . After that, append values to the end 
of the array: [10 20 30 40 50 60 70 80 90]**

In [50]:
original_array = np.array([10, 20, 30])
print("original array:\n",original_array)
extended_array = np.append(original_array, [40, 50, 60, 70, 80, 90])
print("\nTask 3 - (Array after appending):\n", extended_array)

original array:
 [10 20 30]

Task 3 - (Array after appending):
 [10 20 30 40 50 60 70 80 90]


**4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.**

In [48]:
# Task 4
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_array = array1 + array2
print("\nTask 4-(Sum of arrays):\n", sum_array)


Task 4-(Sum of arrays):
 [[14 25 36]
 [44 55 66]
 [74 85 96]]


**5. Create a 3x3 array having values from 10-90 (interval of 10) and store that in array1<br>
Perform the following tasks:<br>
a. Extract the 1st row from the array<br>
b. Extract the last element from the array<br>**"

In [42]:
array1 = np.arange(10, 100, 10).reshape(3, 3)
print("\nTask 5 - 3x3 Array:\n", array1)
firstr = array1[0]
print("\nFirst row:", firstr)
last_element = array1[-1, -1]
print("\nLast element:", last_element)


Task 5 - 3x3 Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

First row: [10 20 30]

Last element: 90
